### ISSUE TITLE
Error in 1:k[i] : NA/NaN argument

### ISSUE THREAD

**Issue by eandresleon** [robinjugas/CNproScan#2]
I obtain this error **Error in 1:k[i] : NA/NaN argument** (which I guess it says that the input parameters are wrong, which is not the case) when invoking the CNproScanCNV function:

```
eandres@nodo00:~/Bioinformatica/EXT/06-EXT-20-Encarni/CVN/bam$ ls -l P8_mapped.sort.coverage
-rw-rw-r-- 1 eandres bioinfo 110041464 Oct  4 14:01 P8_mapped.sort.coverage
eandres@nodo00:~/Bioinformatica/EXT/06-EXT-20-Encarni/CVN/bam$ ls -l P8_mapped.sort.bam*
-rw-rw-r-- 1 eandres bioinfo 338459747 Oct  4 13:49 P8_mapped.sort.bam
-rw-rw-r-- 1 eandres bioinfo     13968 Oct  4 13:54 P8_mapped.sort.bam.bai
eandres@nodo00:~/Bioinformatica/EXT/06-EXT-20-Encarni/CVN/bam$ ls -l ../../Analisis/Genoma/GCA_000750555.1_ASM75055v1_genomic.fna
-rwxrwxr-x 1 bioinfo bioinfo 4689417 Nov 17  2020 ../../Analisis/Genoma/GCA_000750555.1_ASM75055v1_genomic.fna
eandres@nodo00:~/Bioinformatica/EXT/06-EXT-20-Encarni/CVN/bam$ R

R version 4.0.5 (2021-03-31) -- "Shake and Throw"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

> setwd("~/Bioinformatica/EXT/06-EXT-20-Encarni/CVN/bam")
> coverage_file="P8_mapped.sort.coverage"
> bam_file<-"P8_mapped.sort.bam"
> fasta_file="../../Analisis/Genoma/GCA_000750555.1_ASM75055v1_genomic.fna"
> library("CNproScan")
> DF<-CNproScanCNV(coverage_file, bam_file, fasta_file,8)
Error in 1:k[i] : NA/NaN argument
> 

```

**Comment by robinjugas** [comment]
Hi, Would you mind sending me those files used? 
Yeah, the error will be somewhere inside.

**Comment by eandresleon** [comment]
Thanks for your quick response.
I'm trying to create smaller files since P8.bam is a huge file
I'll let u know asap

Kind regards

**Comment by eandresleon** [comment]
Here they are:

Please let me know once you have the files to make them unaccessible

**Comment by robinjugas** [comment]
I have them downloaded.

**Comment by robinjugas** [comment]
Hi, I made some corrections of untreated conditions and now it should work. Just reinstall it:
```
devtools::install_github("robinjugas/CNproScan")
library("CNproScan")
setwd("/...")
coverage_file="P8_mapped_sort.coverage"
bam_file<-"P8_mapped_sort.bam"
fasta_file="NZ_CP009273.fa"
DF<-CNproScanCNV(coverage_file, bam_file, fasta_file,8)
```
Would you please send me a feedback if the package was useful and if you found a CNVs you expected? Thanks!

**Comment by eandresleon** [comment]
Dear Robin,
It works ! I have other samples to analyze, I'll let you know if I have any other problem.
Regarding the expected CNVs ... in fact I expect to have no CNVs ;)

Kind regards

**Comment by eandresleon** [comment]
Thanks for ur help !!! It worked with all files in the experiment. I'm checking now all the results and I'll let you know how useful was this software

**Comment by robinjugas** [comment]
You're welcome. Cheers!
