### ISSUE TITLE
Error in file.exists(bedgraphFile) : invalid 'file' argument

### ISSUE THREAD

**Issue by hayleyjaywilson** [robinjugas/CNproScan#5]
Hello,
I am running the following code in RStudio for CNproScan:
`CNproScanCNV("~/Desktop/hjw58/31741_2_222.coverage", "~/Desktop/hjw58/31741_2_222.sorted.map.bam", "~/Desktop/hjw58/Streptococcus_equi_subsp_equi_4047_v1_renamed.fasta", 4)`
But I am getting the following error:
`Error in file.exists(bedgraphFile) : invalid 'file' argument`

I have tried adding the bedgraphFile to the command as below but results in the same error:
CNproScanCNV("~/Desktop/hjw58/31741_2_222.coverage", "~/Desktop/hjw58/31741_2_222.sorted.map.bam", "~/Desktop/hjw58/Streptococcus_equi_subsp_equi_4047_v1_renamed.fasta", "~/Desktop/hjw58/output_genmap.bedgraph", 4)

Any advice you may have would be appreciated!

**Comment by robinjugas** [comment]
Hi, yeah I see it. I made some updates and havent updated Readme yet. The
new command looks like:
CNproScanCNV(coveragefile,bamFile,fastaFile,GCnorm=TRUE,MAPnorm=FALSE,bedgraphFile=NULL,cores=4)
Cause that bedgraph is needed for mappability correction. So, you have to define MAPnorm=FALSE so you dont need to define bedgraphFile argument. 
Please, give me a  notice if it works then. 
Cheers,
Robin

**Comment by hayleyjaywilson** [comment]
Thanks for the edit. Unfortunately I am having the same outcome:
`CNproScanCNV("~/Desktop/hjw58/31741_2_222.coverage","~/Desktop/hjw58/31741_2_222.sorted.map.bam","~/Desktop/hjw58/Streptococcus_equi_subsp_equi_4047_v1_renamed.fasta",GCnorm=TRUE,MAPnorm=FALSE,bedgraphFile=NULL,cores =4)`

Error in file.exists(bedgraphFile) : invalid 'file' argument

**Comment by robinjugas** [comment]
Sorry, I havent tested it properly at the time of those updates. I updated the argument handling and I think it should be working now. 

CNproScanCNV("~/Desktop/hjw58/31741_2_222.coverage","~/Desktop/hjw58/31741_2_222.sorted.map.bam","~/Desktop/hjw58/Streptococcus_equi_subsp_equi_4047_v1_renamed.fasta",GCnorm=TRUE,MAPnorm=FALSE,cores =4)

should work

**Comment by hayleyjaywilson** [comment]
Hi Robin,

Apologies for the delay. I have updated the package my end and tried again but I am getting the following error:
CNproScanCNV("~/Desktop/hjw58/6903_2_11_CNV_test_sorted_coverage","~/Desktop/hjw58/6903_2_11_CNV_test_sorted.bam","~/Desktop/hjw58/6903_2#11.contigs_spades.fasta",GCnorm=TRUE,MAPnorm=FALSE,cores =4)

Error in if (nchar(seq[1]) > 1) stop("sequence is not a vector of chars") :   missing value where TRUE/FALSE needed

Am I using the correct input files? Particularly the coverage file? But also I'm not sure what is happening with this error.

Thanks

Hayley
________________________________

**Comment by robinjugas** [comment]
Hi, 
maybe send me the files through G drive or something? I will look at it. I think it can be cause I havent add multi chromosome support (yet) so every chromosome should be separately analayzed... 
Robin

**Comment by hayleyjaywilson** [comment]
Hi,

No problem. Do you mind if I send via WeTransfer?

Hayley
________________________________

**Comment by robinjugas** [comment]
Yeah, why not.

**Comment by hayleyjaywilson** [comment]
What email address shall I use?
________________________________

**Comment by robinjugas** [comment]
I downloaded it. I'll look at it today evening or tomorrow.

**Comment by robinjugas** [comment]
Hi!
So, I think the error is in that the reference fasta contains multiple contigs/sequences. But I don't understand, the coverage file is only for contig/chromosome FM204883, but that is nowhere in the reference fasta.
Is it okay?

However, I propose splitting reference fasta:

./splitMULTIFASTA.sh 6903_2#11.contigs_spades.fasta
 and then if you want to, to iteratively use different contigs as references. Although, I dont get it as contigs/chromosomes do not match the coverage 6903_2_11_CNV_test_sorted_coverage  contig.

Something like:

```
setwd("/home/rj/4TB/CNproScan_issue_07_2022/")
library("CNproScan")

coverage_file="wetransfer_cnv-files_2022-07-14_1222/6903_2_11_CNV_test_sorted_coverage"
bam_file<-"wetransfer_cnv-files_2022-07-14_1222/6903_2_11_CNV_test_sorted.bam"

path <- "something "
file.names <- dir(path, pattern =".fasta",recursive = FALSE)
file.names 

for(j in 1:length(file.names)) #
{
  fasta_file <- file.names[j]
  sampleName<-strsplit(file.names[j], "[.]")[[1]][1]
  DF[[j]] <- CNproScanCNV(coverage_file,bam_file,fasta_file,GCnorm=TRUE,MAPnorm=FALSE,cores=8)

}

```
Not sure about handling the output of CNproScanCNV function. 

R. 
[scripts.zip](https://github.com/robinjugas/CNproScan/files/9122721/scripts.zip)

**Comment by hayleyjaywilson** [comment]
Hi Robin,

Thanks for the reply. I see what has happened - I have used the wrong file for coverage. The file FM204883 is my overall reference file for the collection. I saw 'reference fasta' in the instructions and thought you meant exactly that - a reference rather than all the files created being for the query file. That's my misunderstanding. I'll change it and see if that solves it.

But also just to check - my fasta files are all of a single sequence but are drafts so have multiple contigs. I can concatenate it into one though if the program doesn't take multi-contig files? This may also be part of the issue.

I appreciate you taking the time to help me!

Hayley
________________________________

**Comment by robinjugas** [comment]
Hi, I just finished and tested the multi-contig support. 
So you may test it. 
Regarding the fasta headers, I made several assumptions in the function. 
That number of unique header in FASTA, BAM RNAME and COVERAGE file is the same and that they are the same. 
If that is too limiting I will think and update it. 
I can imagine that they are no mapped reads to certain chromosome/contig which will create another issue and I will think about it. 
Just update the package installation and check it. 

Robin

**Comment by hayleyjaywilson** [comment]
Dear Robin,

Many thanks. I will have a look at this and let you know the outcome

Thanks for your assistance and time

Hayley
________________________________
