### ISSUE TITLE
Error  object 'CNV_DF' not found. intalled the updated version aand still the error exists

### ISSUE THREAD

**Issue by Shyamili09** [robinjugas/CNproScan#8]
fasta_file <- "GCA_018093105.1_ASM1809310v1_genomic.fna"
bam_file <- "S.aureus_bat3_r3_sorted.bam"
coverage_file <- "S.aureus_bat3_r3.coverage"
bedgraph_file <- "mapp_genm.bedgraph"
DF <- CNproScanCNV(coverage_file, bam_file, fasta_file, GCnorm=FALSE, MAPnorm=FALSE, ORICnorm=FALSE, cores=4)

Error in CNproScanCNV(coverage_file, bam_file, fasta_file, GCnorm = FALSE,  : 
  object 'CNV_DF' not found

**Comment by robinjugas** [comment]
Hi, I looked into it. 
Can you try BWA aligner instead of minimap? I don't know exactly why, but Rsamtools::ScanBamParam doesn't work on your BAM file...
Alternatively, you can try https://github.com/robinjugas/ProcaryaSV
Best regards,
RJ
